eg25-manager: update LIC_FILES_CHKSUM
* the license file was renamed in:
  https://git.openembedded.org/openembedded-core/commit/?id=5ecf139a31fa7bd813855f1235ea9f434fbcb2e0

* fixes:
  NOTE: recipe eg25-manager-1.0-r0: task do_populate_lic: Started
  WARNING: eg25-manager-1.0-r0 do_populate_lic: Could not copy license file openembedded-core/meta/files/common-licenses/GPL-2.0 to tmp-glibc/work/aarch64-webos-linux/eg25-manager/1.0-r0/license-destdir/eg25-manager/GPL-2.0: [Errno 2] No such file or directory: 'openembedded-core/meta/files/common-licenses/GPL-2.0'
  ERROR: eg25-manager-1.0-r0 do_populate_lic: QA Issue: eg25-manager: LIC_FILES_CHKSUM points to an invalid file: openembedded-core/meta/files/common-licenses/GPL-2.0 [license-checksum]
  ERROR: eg25-manager-1.0-r0 do_populate_lic: Fatal QA errors found, failing task.
  ERROR: Logfile of failure stored in: tmp-glibc/work/aarch64-webos-linux/eg25-manager/1.0-r0/temp/log.do_populate_lic.1760881
  NOTE: recipe eg25-manager-1.0-r0: task do_populate_lic: Failed
  ERROR: Task (meta-pine64-luneos/recipes-connectivity/eg25-manager/eg25-manager.bb:do_populate_lic) failed with exit code '1'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>