u-boot: unbreak rpi builds
* missing override caused all rpi builds to fail like:
  ERROR: Nothing PROVIDES 'trusted-firmware-a' (but /OE/build/luneos-honister/webos-ports/openembedded-core/meta/recipes-bsp/u-boot/u-boot_2021.07.bb DEPENDS on or otherwise requires it)
  trusted-firmware-a was skipped: incompatible with machine raspberrypi4-64 (not in COMPATIBLE_MACHINE)
  trusted-firmware-a was skipped: incompatible with machine raspberrypi4-64 (not in COMPATIBLE_MACHINE)
  NOTE: Runtime target 'luneos-dev-image' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['luneos-dev-image', 'u-boot', 'trusted-firmware-a']
  NOTE: Runtime target 'u-boot-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['u-boot-dev', 'trusted-firmware-a']
  NOTE: Runtime target 'u-boot-env' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['u-boot-env', 'trusted-firmware-a']
  NOTE: Runtime target 'u-boot' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['u-boot', 'trusted-firmware-a']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>