pinephonepro.conf: set FIT_SUPPORTED_INITRAMFS_FSTYPES
* After https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=b0f8d8a4c063936b50d3ec7c066b29157b3c3544
  this needs to match with what IMAGE_FSTYPES we set in initramfs image, in this case:
  recipes-core/images/initramfs-uboot-image.bb:IMAGE_FSTYPES:forcevariable = "cpio.gz.u-boot"

  otherwise do_assemble_fitimage_initramfs fails with:
  ERROR: linux-pinephonepro-5.17-gitAUTOINC+94bfc55e50_3c21ce2225-r0 do_assemble_fitimage_initramfs: Could not find a valid initramfs type for initramfs-uboot-image-pinephonepro, the supported types are: cpio.lz4 cpio.lzo cpio.lzma cpio.xz cpio.zst cpio.gz ext2.gz cpio
  ERROR: linux-pinephonepro-5.17-gitAUTOINC+94bfc55e50_3c21ce2225-r0 do_assemble_fitimage_initramfs: ExecutionError('/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone/webos-ports-env/webos-ports/tmp-glibc/work/pinephonepro-webos-linux/linux-pinephonepro/5.17-gitAUTOINC+94bfc55e50_3c21ce2225-r0/temp/run.do_assemble_fitimage_initramfs.889014', 1, None, None)
  ERROR: Logfile of failure stored in: /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone/webos-ports-env/webos-ports/tmp-glibc/work/pinephonepro-webos-linux/linux-pinephonepro/5.17-gitAUTOINC+94bfc55e50_3c21ce2225-r0/temp/log.do_assemble_fitimage_initramfs.889014
  ERROR: Task (/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone/webos-ports-env/webos-ports/meta-pine64-luneos/recipes-kernel/linux/linux-pinephonepro_git.bb:do_assemble_fitimage_initramfs) failed with exit code '1'

* pinephone doesn't need this, because uses kernel-uboot instead of
  kernel-fitimage set in meta-rockchip:
  #   set  /OE/build/luneos-langdale/webos-ports/meta-rockchip/conf/machine/include/rk3399.inc:14
  #     "kernel-fitimage"

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>