mesa: enable panfrost also for pinephone
* otherwise pp and ppp don't share much sstate as mesa and everything depending on mesa has different signatures
  as shown by:
  openembedded-core/scripts/sstate-diff-machines.sh --tmpdir=tmp-glibc --machines="pinephone pinephonepro qemuarm" --targets=qtwebengine --analyze

ERROR: mesa different signature for task do_configure.sigdata between pinephone and pinephonepro
NOTE: Starting bitbake server...
basehash changed from 409cb65b34dd55e7760703e2c84acfac869e99ec1c041ac425998298ff8d335e to 3df66362406d23a150f2051cbf593e2f59c259b887072e4b66e7ad996823a667
Variable GALLIUMDRIVERS value changed:
@@ -3,8 +3,8 @@
 PACKAGECONFIG{freedreno} = Unset
 PACKAGECONFIG{gallium-llvm} = Unset
 PACKAGECONFIG{kmsro} = Set
-PACKAGECONFIG{lima} = Set
-PACKAGECONFIG{panfrost} = Unset
+PACKAGECONFIG{lima} = Unset
+PACKAGECONFIG{panfrost} = Set
 PACKAGECONFIG{r600} = Unset
 PACKAGECONFIG{v3d} = Unset
 PACKAGECONFIG{vc4} = Unset
Variable PACKAGECONFIG value changed:
@@ -1,4 +1,4 @@
-${@bb.utils.filter('DISTRO_FEATURES', 'wayland vulkan', d)}                    ${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'opengl egl gles gbm dri gallium virgl', '', d)}                    ${@bb.utils.contains('DISTRO_FEATURES', 'x11 opengl', 'x11 dri3', '', d)}                    ${@bb.utils.contains('DISTRO_FEATURES', 'x11 vulkan', 'dri3', '', d)}                    elf-tls               kmsro lima gallium gbm
+${@bb.utils.filter('DISTRO_FEATURES', 'wayland vulkan', d)}                    ${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'opengl egl gles gbm dri gallium virgl', '', d)}                    ${@bb.utils.contains('DISTRO_FEATURES', 'x11 opengl', 'x11 dri3', '', d)}                    ${@bb.utils.contains('DISTRO_FEATURES', 'x11 vulkan', 'dri3', '', d)}                    elf-tls               kmsro panfrost gallium gbm
 DISTRO_FEATURES{opengl} = Set
 DISTRO_FEATURES{vulkan} = Unset
 DISTRO_FEATURES{wayland} = Set

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>