eg25-manager: update SUMMARY, LICENSE and LIC_FILES_CHKSUM
* since the switch from scripts to https://gitlab.com/mobian1/devices/eg25-manager/-/blob/master/COPYING
  the LICENSE is now GPLv3 and we can use COPYING from the repo
  commit 6857ceff38a7fa0d4073b01bd267b829d66aa0da
  Author: Christophe Chapuis <chris.chapuis@gmail.com>
  Date:   Fri Apr 30 15:33:54 2021 +0000

    eg25-manager: use new manager for modem power management

* also fixes compatibility with hardknott where the license file was renamed in:
  https://git.openembedded.org/openembedded-core/commit/?id=5ecf139a31fa7bd813855f1235ea9f434fbcb2e0

* fixes:
  NOTE: recipe eg25-manager-1.0-r0: task do_populate_lic: Started
  WARNING: eg25-manager-1.0-r0 do_populate_lic: Could not copy license file openembedded-core/meta/files/common-licenses/GPL-2.0 to tmp-glibc/work/aarch64-webos-linux/eg25-manager/1.0-r0/license-destdir/eg25-manager/GPL-2.0: [Errno 2] No such file or directory: 'openembedded-core/meta/files/common-licenses/GPL-2.0'
  ERROR: eg25-manager-1.0-r0 do_populate_lic: QA Issue: eg25-manager: LIC_FILES_CHKSUM points to an invalid file: openembedded-core/meta/files/common-licenses/GPL-2.0 [license-checksum]
  ERROR: eg25-manager-1.0-r0 do_populate_lic: Fatal QA errors found, failing task.
  ERROR: Logfile of failure stored in: tmp-glibc/work/aarch64-webos-linux/eg25-manager/1.0-r0/temp/log.do_populate_lic.1760881
  NOTE: recipe eg25-manager-1.0-r0: task do_populate_lic: Failed
  ERROR: Task (meta-pine64-luneos/recipes-connectivity/eg25-manager/eg25-manager.bb:do_populate_lic) failed with exit code '1'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>