linux-firmware-pine64: fix installation paths
* with usrmerge it needs to respect  instead of hardcoding /lib
* fixes:
  ERROR: linux-firmware-pine64-1.0-r0 do_package_qa: QA Issue: linux-firmware-pine64 package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>